### ISSUE TITLE
Breaking update 1.1.3 and how to tune?

### ISSUE THREAD

**Issue by RubenKelevra** [soloam/ha-pid-controller#13]
#11 changed the info on p/i/d as they are now only allowed to be between 0 and 1.

So how are we supposed to tune the algorithm now? Following the [Calibrate the PID](https://github.com/soloam/ha-pid-controller#calibrate-the-pid) section, we probably always have values greater than 1.

This is also a breaking change which isn't mentioned in the [v1.1.3](https://github.com/soloam/ha-pid-controller/releases/tag/v1.1.3) release nodes.

Do old configurations still work with 1.1.3? I mean, the p/i/d values are out of the allowed range now.

**Comment by soloam** [comment]
Yehhh added that info because I was working on the auto tune, and was thinking on a way to make this usable in all situations! And the idea was to make it with value's based on percentage! Actually there is no limitations on that fields! I will remove that info because it's not true! 

Actually nothing changed in this version, only some tweaks too make it more clean in the code and more reliable!

Sorry about the confusion!

**Comment by RubenKelevra** [comment]
Ah! No worries, I was just a bit confused. Thanks for the fast answer! :)
